# Generated by Django 4.2.7 on 2024-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='download_at',
            field=models.DateTimeField(blank=True, help_text='接收时间', null=True, verbose_name='接收时间'),
        ),
    ]
