# Generated by Django 4.2.7 on 2024-04-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_files_download_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="is_sign",
            field=models.BooleanField(
                default=True, help_text="激活", verbose_name="激活"
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="name",
            field=models.CharField(
                help_text="表单名称", max_length=100, verbose_name="表单名称"
            ),
        ),
    ]
