"""
Django settings for Office_system project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import Office_system

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '38c524d233bb7be8b9e0a1d5cacc209c756776be4391b90c38'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# CSRF_TRUSTED_ORIGINS = ['http://10.125.9.198']
# SECURE_HSTS_SECONDS = 3600  # 设置为适当的值
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
SECURE_HSTS_PRELOAD = True
# CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

ALLOWED_HOSTS = ['*']
X_FRAME_OPTIONS = 'ALLOWABLE'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
AUTH_USER_MODEL = 'app01.User'
# Application definition

INSTALLED_APPS = [
    # 上传excle-aql admin
    'import_export',
    'simpleui',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Office_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app01.context_processors.site_header',
                'app01.context_processors.site_title',
                'app01.context_processors.index_title',
            ],
        },
    },
]

WSGI_APPLICATION = 'Office_system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库的类型
        'NAME': 'lxq_personnel_handling',  # 所使用的的数据库的名字
        'USER': 'root',  # 数据库服务器的用户
        'PASSWORD': '970414',  # 密码
        'HOST': '127.0.0.1',  # 主机
        'PORT': '3306',  # 端口
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('zh-hans', _('Simplified Chinese')),
    ('en', _('English')),
    # Add more languages if needed
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# 开发环境才起作用
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),  # 配置静态资源路径，后面逗号一定要加
)

# 生产环境中才起作用
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# 配置上传文件路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
SIMPLEUI_LOGO = ''

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py加入以下内容
# 处理上传excel内容
FILE_UPLOAD_HANDLERS = [
    "django_excel.ExcelMemoryFileUploadHandler",
    "django_excel.TemporaryExcelFileUploadHandler"
]

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
# 隐藏首页的快捷操作和最近动作
# SIMPLEUI_HOME_QUICK = False
# SIMPLEUI_HOME_ACTION = False
# SIMPLEUI_HOME_PAGE = '/upload/'
SIMPLEUI_HOME_TITLE = '濂溪区统一表单系统'
SIMPLEUI_HOME_ICON = 'fa fa-home'
# 关闭登录界面粒子特效
SIMPLEUI_LOGIN_PARTICLES = False
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['文件上传', '上报表单', '表单管理', '组织管理'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'app01',
            'name': '组织管理',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '机构管理',
                    'icon': 'fa fa-th-list',
                    'url': '/admin/app01/institution'
                },
                {
                    'name': '单位管理',
                    'icon': 'fa fa-th-list',
                    'url': '/admin/app01/organization'
                },
                {
                    'name': '部门管理',
                    'icon': 'fa fa-th-list',
                    'url': '/admin/app01/department'
                },
                {
                    'name': '用户管理',
                    'icon': 'fa fa-user',
                    'url': '/admin/app01/user/'
                },

            ]
        },
        {
            'name': '表单管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '表单管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/app01/forms/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': '上报表单',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '上报表单管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/app01/files/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        # {
        #     'name': '文件上传',
        #     'icon': 'fa fa-th-list',
        #     'models': [
        #         {
        #             'name': '文件上传',
        #             # 注意url按'/admin/应用名小写/模型名小写/'命名。
        #             'url': '/upload/',
        #             'icon': 'fa fa-tasks'
        #         },
        #     ]
        # },

    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'DEBUG',
    },
}
